services:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
      - ./loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml

volumes:
  loki-data: