services:
  msr:
    container_name: msr
    image: $MSR_IMAGE
    ports:
      - "15555:5555"
      - "15556:6666"
      - "15557:7777"
    # environment:
    #   - SW_AGENT_COLLECTOR_ESTABLISH_CLOUD_COMMUNICATION=false
    #   - SW_AGENT_EXTERNAL_ESTABLISH_COMMUNICATION=true
    #   - SW_AGENT_OTEL_ENDPOINT=http://otel-collector:4318/v1/traces
    #   - SW_AGENT_OTEL_HEADERS=Content-Type#application/x-protobuf
    #   - SW_AGENT_EXT_SYSTEM_USER=
    #   - SW_AGENT_EXT_SYSTEM_PASSWORD=
    #   - SW_AGENT_EXTERNAL_SUPPORT_LONG_ID=false
    #   - SW_AGENT_EXTERNAL_API_ERROR_CODES=502,503,504
    #   - SW_AGENT_OTEL_RESOURCE_ATTRIBUTES=service.name#msr-otel, service.namespace#default
    #   - SW_AGENT_TRACE_TRANSFER_INTERVAL=1000
    volumes:
      - ./msr/application.properties:/opt/softwareag/IntegrationServer/application.properties
      - $HOME/licenses/msr-license.xml:/opt/softwareag/IntegrationServer/config/licenseKey.xml:ro
      - $HOME/shared/files:/files
      - msr-logs:/opt/softwareag/IntegrationServer/logs
#      - $HOME/git/sttHelloWorld:/opt/softwareag/IntegrationServer/packages/sttHelloWorld
#      - $HOME/git/sttKafka:/opt/softwareag/IntegrationServer/packages/sttKafka
#      - ./msr/es-truststore.jks:/opt/softwareag/IntegrationServer/config/es-truststore.jks:ro
#      - ./msr/streaming.cnf:/opt/softwareag/IntegrationServer/packages/sttKafka/config/streaming.cnf
    depends_on:
      - umserver

volumes:

