global:
  scrape_interval: 10s 

scrape_configs:
  - job_name: 'container_metrics'
    static_configs:
      - targets: ['msr-sandbox:5555'] 
        labels:
          product: 'msr'
      - targets: ['umserver:9200']  
        labels:
          product: 'um'
      - targets: ['apigw11:5555']  
        labels:
          product: 'apigw'

