services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    volumes:
      - ./otelcollector/tempo.yml:/etc/tempo/tempo.yml
      - tempo-data:/var/tempo/traces
    ports:
      - "3200:3200"   
    command: -config.file=/etc/tempo/tempo.yml

volumes:
  tempo-data: